### ISSUE TITLE
看来OSS的SDK不支持多文件上传啊。

### ISSUE THREAD

**Issue by mrmarktyy** [WiFiUncle/ossUploader#4]
代码里是用遍历的方法，hmm.. 有点问题
如果再考虑出错处理 （比如重传某个文件），那更麻烦了

**Comment by WiFiUncle** [comment]
oss sdk 不支持多文件上传。

这个demo是用for循环的，emm····
工程里是 批量上传+ 上传失败可以再次上传。   自行设置批量上传文件数，和上传错误重试次数。

上传失败可以用个数组记录上传错误的文件。到时在重新上传下那个数组里面的文件，记录成功数量、失败数量、总数等去判断  这次上传是否全部上传完成

**Comment by mrmarktyy** [comment]
谢谢回复
