### ISSUE TITLE
怎么定义上传文件的文件名

### ISSUE THREAD

**Issue by ghost** [WiFiUncle/ossUploader#5]
怎么自定义上传文件的文件名？

**Comment by WiFiUncle** [comment]
js/index.js 上传文件方法

`if( uploadType != FOLDER) {
          filePath += file.name;
      } else { //上传文件夹
          filePath = filePath + this.getParentDirName(file) + file.name;
      }`
这里拼接filePath，你自己拼接下。  我没试过哈

**Comment by xue-y** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WiFi_Uncle"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月23日(星期一) 中午11:20
收件人:&nbsp;"WiFiUncle/ossUploader"<ossUploader@noreply.github.com&gt;;
抄送:&nbsp;"星海"<php.develop@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WiFiUncle/ossUploader] 怎么定义上传文件的文件名 (#5)




js/index.js 上传文件方法
 
if( uploadType != FOLDER) { filePath += file.name; } else { //上传文件夹 filePath = filePath + this.getParentDirName(file) + file.name; }
 这里拼接filePath，你自己拼接下。  我没试过哈
